LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

SRC = \
    native-lib.cpp

INCLUDES = \
    $(LOCAL_PATH) \


EXPORT_INCLUDES = $(INCLUDES)

STATIC_LIBRARIES =

SHARED_LIBRARIES =

LOCAL_MODULE := native-lib
LOCAL_SRC_FILES := $(SRC)
LOCAL_C_INCLUDES := $(INCLUDES)
LOCAL_EXPORT_C_INCLUDES := $(EXPORT_INCLUDES)
LOCAL_STATIC_LIBRARIES := $(STATIC_LIBRARIES)
LOCAL_SHARED_LIBRARIES := $(SHARED_LIBRARIES)

# LOCAL_CPPFLAGS := \
    -DNULL=0 -DSOCKLEN_T=socklen_t -DNO_SSTREAM -DBSD=1 -DNO_SSTREAM -fexceptions -DANDROID -DXLOCALE_NOT_USED

# LOCAL_MODULE_TAGS := optional

LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
